# Lessons about functions of Numpy



### Source book : Python Data Science HandBook By: Jaker VanderPlas

In [96]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [97]:
type(L)

list

In [98]:
#how to create a list

L2 = [str(z) for z in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [99]:
type(L2)

list

In [100]:
#use () to create a list
for value in range(1,5):    
  print(value)

1
2
3
4


In [101]:
import array

L3 = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
import numpy as np

In [103]:
np.array([1, 3, 4, 6, 11, 95, 46, 23])

array([ 1,  3,  4,  6, 11, 95, 46, 23])

In [104]:
np.arange(0,40,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [105]:
np.linspace(0, 1, 5)  # Create an array of five values evenly spaced between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [106]:
np.random.random((5,5))

array([[0.61785601, 0.40297491, 0.43481653, 0.98403179, 0.52236689],
       [0.67915227, 0.43879544, 0.48288683, 0.66542187, 0.13209955],
       [0.8171501 , 0.62646272, 0.37618941, 0.62616374, 0.9897257 ],
       [0.82785915, 0.8430057 , 0.11882973, 0.78231263, 0.83799328],
       [0.42604735, 0.51089362, 0.96132588, 0.63089036, 0.89086967]])

In [107]:
np.random.randint(0, 20,( 4,4))   #array of random integers in the interval

array([[17,  4, 14,  8],
       [ 9, 11, 14,  7],
       [ 9,  7, 17,  8],
       [ 1,  8, 18,  0]])

In [108]:
## Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.random.seed()


In [111]:
# One-dimensional array
x1 = np.random.randint(10, size= 6)  
x1

array([0, 4, 0, 2, 9, 8])

In [112]:
# Two-dimensional array
x2 = np.random.randint(10, size = (3, 6))
x2

array([[9, 7, 1, 0, 6, 9],
       [1, 9, 9, 3, 3, 8],
       [6, 5, 7, 0, 5, 5]])

In [113]:
# Three-dimensional array
x3 = np.random.randint(10, size=(3,4,5))      # 3 array with colums 4x5 in random numbers of 0 to 9
x3

array([[[3, 7, 9, 8, 5],
        [6, 3, 2, 2, 1],
        [2, 4, 5, 2, 2],
        [8, 8, 1, 2, 6]],

       [[9, 9, 8, 9, 0],
        [9, 7, 7, 7, 1],
        [2, 9, 1, 8, 8],
        [1, 1, 7, 5, 8]],

       [[6, 5, 3, 9, 5],
        [7, 1, 3, 6, 9],
        [6, 9, 4, 0, 5],
        [7, 5, 3, 9, 6]]])

In [114]:
print('x3 ndim:' , x3.ndim)     #dimensions
print('x3 shape' , x3.shape)    #size of each dimension
print('x3 size', x3.size)       #total size of the array  
print('x3 dtype:', x3.dtype)   #type of array
print('x3 itemsize:', x3.itemsize)  #size in bytes of each list
print('x3 nbytes', x3.nbytes)       #total size in bytes of the array

x3 ndim: 3
x3 shape (3, 4, 5)
x3 size 60
x3 dtype: int64
x3 itemsize: 8
x3 nbytes 480


In [115]:
x3 = np.arange(10)
x3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
# first five elements
x3[:5]

array([0, 1, 2, 3, 4])

In [117]:
# elements after index 5
x3[5:]

array([5, 6, 7, 8, 9])

In [118]:
# middle subarray
x3[3:7]

array([3, 4, 5, 6])

In [119]:
#2 in 2
x3[::2]

array([0, 2, 4, 6, 8])

In [120]:
x3[2::]  #2 until the end

array([2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
#starting at index 1 , 2 in 2
x3[1::2]

array([1, 3, 5, 7, 9])

In [122]:
x3[2::1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
# all elements, reversed
x3[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [124]:
x3[:-5]

array([0, 1, 2, 3, 4])

In [125]:
# reversed every other from index 5
x3[5::-1]

array([5, 4, 3, 2, 1, 0])

In [126]:
x2

array([[9, 7, 1, 0, 6, 9],
       [1, 9, 9, 3, 3, 8],
       [6, 5, 7, 0, 5, 5]])

In [127]:
# two rows, three columns
x2[:2, :3]

array([[9, 7, 1],
       [1, 9, 9]])

In [128]:
# first column of x2
x2[:, 0]

array([9, 1, 6])

In [129]:
# first row of x2
x2[0, :]

array([9, 7, 1, 0, 6, 9])

In [130]:
#extract a 2×2 subarray
x2_sub = x2[:2 , :2]
x2_sub

array([[9, 7],
       [1, 9]])

In [131]:
#modify this subarray , the "8" to 99
x2_sub[0, 0] = 99
x2

array([[99,  7,  1,  0,  6,  9],
       [ 1,  9,  9,  3,  3,  8],
       [ 6,  5,  7,  0,  5,  5]])

In [132]:
#using reshape
b1 = np.arange(1,10).reshape((3, 3))
b1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
#oncatenation
x = np.array([1, 6 , 9])
y = np.array([3, 9 , 1])

np.concatenate([x, y])

array([1, 6, 9, 3, 9, 1])

In [134]:
grid = np.array([[9,8,7],
                [6,4,4]])
np.concatenate([grid, grid])

array([[9, 8, 7],
       [6, 4, 4],
       [9, 8, 7],
       [6, 4, 4]])

In [135]:
#split array
d = [1, 5 ,3 ,7, 8 ,9 , 0, 3, 7]
g1, g2, g3 = np.split(d, [3,5])
print ( g1, g2, g3)

[1 5 3] [7 8] [9 0 3 7]


In [136]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [137]:
#getting 2 rooms
upper, lower = np.vsplit(grid, [2])
print (upper)


[[0 1 2 3]
 [4 5 6 7]]


In [138]:
print(lower)

[[ 8  9 10 11]
 [12 13 14 15]]


In [139]:
x =np.arange(4)
print("x  =", x)


x  = [0 1 2 3]


In [140]:
print("x + 5 =", x + 5)

x + 5 = [5 6 7 8]


In [141]:
print("x - 5 =", x - 5)

x - 5 = [-5 -4 -3 -2]


In [142]:
print("x * 2 = ", x * 2)

x * 2 =  [0 2 4 6]


In [143]:
print("x / 2 = ", x / 2)

x / 2 =  [0.  0.5 1.  1.5]


In [144]:
np.add(x , 2)

array([2, 3, 4, 5])

## #Trigonometric functions 


In [145]:
theta = np.linspace(0,np.pi, 3 )
theta

array([0.        , 1.57079633, 3.14159265])

In [146]:
print("sin (theta) = ", np.sin(theta))

sin (theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [147]:
print("cos(theta) = ", np.cos(theta))

cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [148]:
print("tan(theta) = ", np.tan(theta))

tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [149]:
m = [1, 2, 3]
m

[1, 2, 3]

In [150]:
print("e^m = ", np.exp(m))

e^m =  [ 2.71828183  7.3890561  20.08553692]


In [151]:
print("2^m = ", np.exp2(m))

2^m =  [2. 4. 8.]


In [152]:
print("3^m =", np.power(3, m))

3^m = [ 3  9 27]


In [153]:
print("ln(m) = ", np.log(m))

ln(m) =  [0.         0.69314718 1.09861229]


In [154]:
print("log10(m)", np.log(10))

log10(m) 2.302585092994046


In [155]:
print("exp(m) - 1 ", np.expm1(m) )

exp(m) - 1  [ 1.71828183  6.3890561  19.08553692]


In [156]:
print("log(1 + x) =", np.log1p(x))

log(1 + x) = [0.         0.69314718 1.09861229 1.38629436]


In [157]:
from scipy import special      #more functions
m

[1, 2, 3]

In [158]:
print("gamma(m) =", special.gamma(m))

gamma(m) = [1. 1. 2.]


In [159]:
#integral of Gaussian)
print('erf(m) =', special.erf(m))

erf(m) = [0.84270079 0.99532227 0.99997791]


In [160]:
#unfunc
q = np.arange(5)
o = np.empty(5)
np.multiply(q , 10, out = o)


array([ 0., 10., 20., 30., 40.])

In [161]:
#agregate to reduce it's like +1+2+3+4.... = x
q = np.arange(1,6)
np.add.reduce(q)


15

In [162]:
#multiply 5x4x3x2x1....
np.multiply.reduce(q)

120

In [163]:
np.add.accumulate(q)

array([ 1,  3,  6, 10, 15])

In [164]:
np.multiply.accumulate(q)

array([  1,   2,   6,  24, 120])

In [165]:
q

array([1, 2, 3, 4, 5])

In [166]:
np.multiply.outer(q, q)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

##Summing the Values in an Array

In [167]:
L = np.random.random(100)
sum(L)

48.115446511086645

In [168]:
np.sum(L)

48.11544651108663

In [169]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array) #np.sum is aware of multiple array dimensions

1 loop, best of 3: 148 ms per loop
1000 loops, best of 3: 359 µs per loop


In [170]:
min(big_array)


1.3394481724882112e-06

In [171]:
max(big_array)

0.9999985384372744

In [172]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 3: 95.1 ms per loop
1000 loops, best of 3: 427 µs per loop
