# Some lessons about Numpy
### Source book : Python Data Science HandBook By: Jaker VanderPlas

In [ ]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(L)

list

In [ ]:
#how to create a list

L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
type(L2)

list

In [ ]:
#use () to create a list
for value in range(1,5):    
  print(value)

1
2
3
4


In [ ]:
import array

L3 = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

In [ ]:
np.array([1, 3, 4, 6, 11, 95, 46, 23])

array([ 1,  3,  4,  6, 11, 95, 46, 23])

In [ ]:
np.arange(0,40,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [ ]:
np.linspace(0, 1, 5)  # Create an array of five values evenly spaced between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((5,5))

array([[0.85338598, 0.34505979, 0.51254063, 0.20143165, 0.37484312],
       [0.92685791, 0.24875474, 0.84671041, 0.50343637, 0.98479909],
       [0.98592159, 0.18805936, 0.07719849, 0.82872225, 0.98293659],
       [0.0292929 , 0.41190406, 0.27102798, 0.51332367, 0.63077505],
       [0.78811631, 0.57894271, 0.79604568, 0.43333088, 0.6135476 ]])

In [ ]:
np.random.randint(0, 20,( 4,4))   #array of random integers in the interval

array([[ 5, 14,  2,  8],
       [14, 14, 12,  5],
       [ 0,  1, 15,  5],
       [14, 16,  0,  5]])

In [ ]:
## Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])